#Update the email address and password to use
#Go to your Google Account → Security
#Enable 2-Step Verification if not already enabled
#Then go to "App passwords" and generate a new password specifically for your Spring Boot application
#Use that generated password in your configuration
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: your.actual.email@gmail.com
        password: your-16-character-app-password
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
