spring:
    mail:
        properties:
            mail:
                smtp:
                    starttls:
                        enable: 'true'
                    auth: 'true'
        host: smtp.gmail.com
        username: email-address
        password: password
        port: '587'
#    datasource:
#        username: root
#        url: jdbc:mysql://localhost:3306/email
#        password: password
#    application:
#        name: email
#    jpa:
#        hibernate:
#            ddl-auto: update
